### ISSUE TITLE
Out-of screen listed hash algorithms cannot not be viewed

### ISSUE THREAD

**Issue by Ricky-Tigg** [tristanheaven/gtkhash#35]
_Component_: gtkhash.x86_64  1.2-1.fc31 @fedora; _Tested on_: Gnome standard v. 3.34.1 under both Wayland and X servers

- Under Edit | Preferences,  all available hash algorithms have been selected; as a result, the application's window is tall enough not to fit on the screen. Interface is lacking a **vertical scroll-bar** thus results listed out-of the screen cannot not be viewed. Window is displayed from its top border.

- While window is in that state, and while Help | About is opened, that last window is not movable.

**Comment by tristanheaven** [comment]
Thanks. I've added vertical scrolling, but I'm not sure what you meant by your second point. Is that a separate issue?

**Comment by Ricky-Tigg** [comment]
Second observation may be an issue. It might be wiser waiting an availability on my system of a release version containing an up to come fix.

I realize afterwards what shall be the situation once that bar will be implemented. That bar won't be able to reach the bottom of the application window, because the top of the application window, which will be at the top of the screen frame, won't have any moving marge left on top of it.

A **definitive** fix would then involve, along with existent bar, the application window's top and bottom limits to be re-sizable to smaller.

**Comment by tristanheaven** [comment]
Here's what it looks like now:
![vert-scroll-normal](https://user-images.githubusercontent.com/26687/70473592-42d18f00-1ac9-11ea-8780-47cee448ad33.png)

I've found that with this change, enabling extra algorithms will always extend the scrolled area instead of increasing the window height.

This is the minimum window size:
![vert-scroll-min-file](https://user-images.githubusercontent.com/26687/70473613-4ebd5100-1ac9-11ea-8b01-6ba34cdddbe0.png)

![vert-scroll-min-text](https://user-images.githubusercontent.com/26687/70473617-51b84180-1ac9-11ea-9bfb-d4fde3b0966a.png)

**Comment by Ricky-Tigg** [comment]
Good observation.
