### ISSUE TITLE
[Packaging] Make this application available as flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [tristanheaven/gtkhash#45]
Hellow.

I would like to suggest on you to make "GtkHash" officially available by you as official flatpak package on FlatHub.

Flatpak is a universal Linux package that compatible with almost all Linux distros ...... By making Jitsi Meet available as flatpak on FlatHub, it will be available for almost all Linux distros & users.

Flatpak is secure package system with default sandbox. It offer users automatic updates, & being independent from system version.

FlatHub home page is:
https://www.flathub.org/home
FlatHub repositories are here:
https://github.com/flathub
To post your flatpak on FlatHub, you have to make PR on:
https://github.com/flathub/flathub/pulls

Flatpak documentation here:
https://docs.flatpak.org/en/latest/

Flatpak is easier to be packaged than AppImage & flatpaks on FlatHub all are signed & the administrations of FlatHub prefer for open source packages to be deterministic (fully reproducible).

**Comment by tristanheaven** [comment]
Yes, I intend to do this now that the Snap is working.
Thanks

**Comment by Nokia808** [comment]
@tristanheaven 
Thank you too much for your positive response !

**Comment by tristanheaven** [comment]
Done - https://github.com/flathub/org.gtkhash.gtkhash

**Comment by Nokia808** [comment]
@tristanheaven 
Many thanks ! 
Only one question: does flatpak package is fully functional as .rpm package or it has a limitation(s) ?

**Comment by tristanheaven** [comment]
The main limitation is that it doesn't include the file manager extension for Nautilus, Nemo, etc.

Also it might not be possible to select files requiring a network connection (e.g. sftp:// smb://) due to the current sandbox permissions. I'm not sure what is required to fix that.

I think everything else is working.

**Comment by Nokia808** [comment]
@tristanheaven 
Dear developer, I think that the best way to solve these issues is to discuss them with Flatpak upstream at:
https://github.com/flatpak/flatpak/issues
& on FlatHub forum at:
https://discourse.flathub.org/

If Flatpak will not removed such limitations by it's design, then it's goal to be a replacement for distros specific formats will certainly end by failure. How it will replace them & it is not able to offer all their functionalities ??

**Comment by tristanheaven** [comment]
The network permission is probably something I could add, but I think it would be better if the user could decide whether to allow it on their system. I had to add full local filesystem access as a requirement because the sandbox feature (XDG portal) doesn't work for basic things like drag-and-drop. Hopefully they'll improve the integration for applications in future.
